/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kitchen;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JToggleButton;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class CustomerDashboard extends JFrame {

    Customer customer;
    restaurantAgent DATA;
    HashMap<JToggleButton,Table> ButtonMap;
    ArrayList<JToggleButton> toggles;
    DefaultListModel<String> DishModel = new DefaultListModel<>();
    DefaultListModel<String> OrderModel = new DefaultListModel<>();
    HashMap<String,Dish> DishMap;
    Orders orders = new Orders();
    Tables tables = new Tables();
    Order order = new Order();
    Table table = new Table();
    ArrayList<Order> orderlist;
    ArrayList<Table> tablelist = new ArrayList<>();
    ArrayList<Dish> dishlist = new ArrayList<>();
    
   public CustomerDashboard(Customer customer , restaurantAgent DATA) {
       
       try {
       this.orderlist= new ArrayList<>();
       this.orderlist = DATA.getOrders().getOrders();
       }catch(Exception e){
         this.orderlist= new ArrayList<>();
//       this.orderlist = null;    
       }
       this.tablelist = DATA.getTables().getTables();
       this.customer=customer;
       this.DATA=DATA;
        initComponents();
        jButtonGroup1.add(jRadioButton1);
        jButtonGroup1.add(jRadioButton2);
        this.toggles = new ArrayList<>();
        this.ButtonMap = new HashMap<>();
        toggles.add(B1);
        toggles.add(B2);
        toggles.add(B3);
        toggles.add(B4);
        toggles.add(B5);
        toggles.add(B6);
        toggles.add(B7);
        for(int i=0 ; i<toggles.size();i++){
        ButtonMap.put(toggles.get(i),DATA.getTables().getTables().get(i));
        }
        PlaceOrderbtn.setVisible(false);
        for(int i=0 ; i<toggles.size(); i++){
            toggles.get(i).setVisible(false);
        }
        for (Map.Entry<JToggleButton, Table> entry : ButtonMap.entrySet()){
            buttonGroup1.add(entry.getKey());
        }
        DishList.setModel(DishModel);
        for (Dish dish : DATA.getDishes().getDishes()){
            DishModel.addElement(dish.getDishName() + "   " + dish.getDishPrice());
        }
        this.DishMap = new HashMap<>();
        for(int i=0;i<DishModel.size();i++)
            DishMap.put(DishModel.get(i),DATA.getDishes().getDishes().get(i));
        OrderList.setModel(OrderModel);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        CustomerTabs = new javax.swing.JTabbedPane();
        ReserveTable = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Showbtn = new javax.swing.JButton();
        B1 = new JToggleButton();
        B2 = new JToggleButton();
        B3 = new JToggleButton();
        B4 = new JToggleButton();
        B5 = new JToggleButton();
        B6 = new JToggleButton();
        B7 = new JToggleButton();
        PlaceOrderbtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        PlaceOrder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ShowOrderbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DishList = new javax.swing.JList<>();
        Addbtn = new javax.swing.JButton();
        Removebtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderList = new javax.swing.JList<>();
        OrderDetails = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Resetbtn = new javax.swing.JButton();
        Confirmbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Details = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        CustomerTabs.setBackground(new java.awt.Color(102, 0, 51));
        CustomerTabs.setForeground(new java.awt.Color(255, 255, 255));
        CustomerTabs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        ReserveTable.setBackground(new java.awt.Color(102, 0, 51));

        jLabel2.setBackground(new java.awt.Color(102, 0, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Reserve Your table");

        jLabel1.setBackground(new java.awt.Color(102, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number Of Seats");

        jLabel4.setBackground(new java.awt.Color(102, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Smoking ?");

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });
        jSpinner1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinner1PropertyChange(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(102, 0, 51));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("YES");

        jRadioButton2.setBackground(new java.awt.Color(102, 0, 51));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("NO");

        Showbtn.setBackground(new java.awt.Color(255, 255, 255));
        Showbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Showbtn.setForeground(new java.awt.Color(102, 0, 51));
        Showbtn.setText("SHOW");
        Showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowbtnActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B1.setForeground(new java.awt.Color(102, 0, 51));
        B1.setText("Table ");
        B1.setMaximumSize(new java.awt.Dimension(120, 85));
        B1.setMinimumSize(new java.awt.Dimension(120, 85));

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B2.setForeground(new java.awt.Color(102, 0, 51));
        B2.setText("Table ");
        B2.setMaximumSize(new java.awt.Dimension(120, 85));
        B2.setMinimumSize(new java.awt.Dimension(120, 85));

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B3.setForeground(new java.awt.Color(102, 0, 51));
        B3.setText("Table ");
        B3.setMaximumSize(new java.awt.Dimension(120, 85));
        B3.setMinimumSize(new java.awt.Dimension(120, 85));

        B4.setBackground(new java.awt.Color(255, 255, 255));
        B4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B4.setForeground(new java.awt.Color(102, 0, 51));
        B4.setText("Table ");
        B4.setMaximumSize(new java.awt.Dimension(120, 85));
        B4.setMinimumSize(new java.awt.Dimension(120, 85));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B5.setForeground(new java.awt.Color(102, 0, 51));
        B5.setText("Table");
        B5.setMaximumSize(new java.awt.Dimension(120, 85));
        B5.setMinimumSize(new java.awt.Dimension(120, 85));

        B6.setBackground(new java.awt.Color(255, 255, 255));
        B6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B6.setForeground(new java.awt.Color(102, 0, 51));
        B6.setText("Table ");
        B6.setMaximumSize(new java.awt.Dimension(120, 85));
        B6.setMinimumSize(new java.awt.Dimension(120, 85));

        B7.setBackground(new java.awt.Color(255, 255, 255));
        B7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B7.setForeground(new java.awt.Color(102, 0, 51));
        B7.setText("Table ");
        B7.setMaximumSize(new java.awt.Dimension(120, 85));
        B7.setMinimumSize(new java.awt.Dimension(120, 85));

        PlaceOrderbtn.setBackground(new java.awt.Color(255, 255, 255));
        PlaceOrderbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PlaceOrderbtn.setForeground(new java.awt.Color(102, 0, 51));
        PlaceOrderbtn.setText("Place Order");
        PlaceOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderbtnActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(102, 0, 51));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReserveTableLayout = new javax.swing.GroupLayout(ReserveTable);
        ReserveTable.setLayout(ReserveTableLayout);
        ReserveTableLayout.setHorizontalGroup(
            ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveTableLayout.createSequentialGroup()
                .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReserveTableLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(ReserveTableLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Back)
                        .addGap(333, 333, 333)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ReserveTableLayout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(PlaceOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ReserveTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReserveTableLayout.createSequentialGroup()
                        .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReserveTableLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReserveTableLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(Showbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324))
                    .addGroup(ReserveTableLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ReserveTableLayout.setVerticalGroup(
            ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveTableLayout.createSequentialGroup()
                .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReserveTableLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Back)
                        .addGap(47, 47, 47)
                        .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReserveTableLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Showbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(ReserveTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(PlaceOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        CustomerTabs.addTab("Table", ReserveTable);

        PlaceOrder.setBackground(new java.awt.Color(102, 0, 51));

        jLabel3.setBackground(new java.awt.Color(102, 0, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please Place Your Order");

        ShowOrderbtn.setBackground(new java.awt.Color(255, 255, 255));
        ShowOrderbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowOrderbtn.setForeground(new java.awt.Color(102, 0, 51));
        ShowOrderbtn.setText("Show Order Details");
        ShowOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowOrderbtnActionPerformed(evt);
            }
        });

        DishList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DishList.setForeground(new java.awt.Color(102, 0, 51));
        jScrollPane1.setViewportView(DishList);

        Addbtn.setBackground(new java.awt.Color(255, 255, 255));
        Addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(102, 0, 51));
        Addbtn.setText("ADD");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        Removebtn.setBackground(new java.awt.Color(255, 255, 255));
        Removebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Removebtn.setForeground(new java.awt.Color(102, 0, 51));
        Removebtn.setText("REMOVE");
        Removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovebtnActionPerformed(evt);
            }
        });

        OrderList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OrderList.setForeground(new java.awt.Color(102, 0, 51));
        jScrollPane2.setViewportView(OrderList);

        javax.swing.GroupLayout PlaceOrderLayout = new javax.swing.GroupLayout(PlaceOrder);
        PlaceOrder.setLayout(PlaceOrderLayout);
        PlaceOrderLayout.setHorizontalGroup(
            PlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlaceOrderLayout.createSequentialGroup()
                .addGroup(PlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlaceOrderLayout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(ShowOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PlaceOrderLayout.createSequentialGroup()
                        .addGroup(PlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlaceOrderLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addGroup(PlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Removebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PlaceOrderLayout.createSequentialGroup()
                                .addGap(432, 432, 432)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        PlaceOrderLayout.setVerticalGroup(
            PlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlaceOrderLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlaceOrderLayout.createSequentialGroup()
                        .addGroup(PlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlaceOrderLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(Removebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PlaceOrderLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlaceOrderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)))
                .addComponent(ShowOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PlaceOrderLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CustomerTabs.addTab("Place Order", PlaceOrder);

        OrderDetails.setBackground(new java.awt.Color(102, 0, 51));

        jLabel6.setBackground(new java.awt.Color(102, 0, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thank You For Visiting Us.");

        Resetbtn.setBackground(new java.awt.Color(255, 255, 255));
        Resetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Resetbtn.setForeground(new java.awt.Color(102, 0, 51));
        Resetbtn.setText("Reset");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });

        Confirmbtn.setBackground(new java.awt.Color(255, 255, 255));
        Confirmbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Confirmbtn.setForeground(new java.awt.Color(102, 0, 51));
        Confirmbtn.setText("Confirm");
        Confirmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmbtnActionPerformed(evt);
            }
        });

        Details.setEditable(false);
        Details.setColumns(20);
        Details.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        Details.setForeground(new java.awt.Color(102, 0, 51));
        Details.setRows(5);
        jScrollPane3.setViewportView(Details);

        javax.swing.GroupLayout OrderDetailsLayout = new javax.swing.GroupLayout(OrderDetails);
        OrderDetails.setLayout(OrderDetailsLayout);
        OrderDetailsLayout.setHorizontalGroup(
            OrderDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361))
            .addGroup(OrderDetailsLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(OrderDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OrderDetailsLayout.createSequentialGroup()
                        .addComponent(Confirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(Resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        OrderDetailsLayout.setVerticalGroup(
            OrderDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderDetailsLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(OrderDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        CustomerTabs.addTab("Order Details", OrderDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowbtnActionPerformed
        // TODO add your handling code here:
        PlaceOrderbtn.setVisible(true);
        for(int i=0 ; i<toggles.size(); i++){
            toggles.get(i).setVisible(false);
        }
        for (Map.Entry<JToggleButton, Table> entry : ButtonMap.entrySet()) {
            entry.getKey().setText("<html><center>" + "Number " + entry.getValue().getTableNum() + "<br>" + "Seats " 
                    +entry.getValue().getSeatsNum() + "</html>" );
            if (jRadioButton1.isSelected()){
                if((int)jSpinner1.getValue() <= entry.getValue().getSeatsNum() && entry.getValue().isSmoking()==true && entry.getValue().isAvailable() == true)
                    entry.getKey().setVisible(true);
            }
            else if (jRadioButton2.isSelected()){
                if((int)jSpinner1.getValue() <= entry.getValue().getSeatsNum() && entry.getValue().isSmoking() == false && entry.getValue().isAvailable() == true)
                    entry.getKey().setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null,"Sorry , No Available Tables By These Properties For Now");
        }
    }//GEN-LAST:event_ShowbtnActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void jSpinner1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinner1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1PropertyChange

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        // TODO add your handling code here:  
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void PlaceOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderbtnActionPerformed
        // TODO add your handling code here:
        CustomerTabs.setSelectedIndex(1);
    }//GEN-LAST:event_PlaceOrderbtnActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:       
        Dish dish = DishMap.get(DishList.getSelectedValue());
        if (dish != null){
        OrderModel.addElement(DishList.getSelectedValue());
        dishlist.add(dish);
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Select A Dish");
        }
    }//GEN-LAST:event_AddbtnActionPerformed

    private void RemovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovebtnActionPerformed
        // TODO add your handling code here:
        try{
        dishlist.remove(OrderList.getSelectedIndex()); //try & catch for empty list
        OrderModel.removeElementAt(OrderList.getSelectedIndex()); 
        }catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null,"Nothing To Remove");
        }
    }//GEN-LAST:event_RemovebtnActionPerformed

    private void ShowOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowOrderbtnActionPerformed
        // TODO add your handling code here:
        CustomerTabs.remove(0);
        CustomerTabs.remove(0);
        CustomerTabs.add("Order Details",OrderDetails);
        order.setPriceWithoutTax(0);
        order.setOrderPrice(0);
        boolean flag=false;
        for (int i=0 ; i<toggles.size();i++){
            if(toggles.get(i).isSelected()){
                if(dishlist.size()==0)
                    JOptionPane.showMessageDialog(null,"Please Make An Order");
                else{
                   
                    order.setDishes(dishlist);
                    order.calcOrderPrice();
                    order.calcTotalOrderPrice();
                      String text1=("Customer Name  :  " + customer.getName() + "\n" + 
                      "Table Number  :  " + ButtonMap.get(toggles.get(i)).getTableNum() + "\n");
                      String text2 = "";
                      table.setTableNum(ButtonMap.get(toggles.get(i)).getTableNum());
                      table.setSeatsNum(ButtonMap.get(toggles.get(i)).getSeatsNum());
                      table.setSmoking(ButtonMap.get(toggles.get(i)).isSmoking());
                      table.setAvailable(false);
                      order.setTableNum(ButtonMap.get(toggles.get(i)).getTableNum());
                      for(int j=0;j<dishlist.size();j++){
                      text2 = ( text2 + dishlist.get(j).getDishName() + "  " + 
                      dishlist.get(j).getDishPrice() + "\n");
                      }
                      String text3 =("Price Without Taxes  :  " + order.getPriceWithoutTax() + "\n" +
                      "Price after Taxes  :  " + order.getOrderPrice());
                      Details.setText(text1 + text2 + text3);
                }
                flag=true;
                break;
            }
        }
        if(!flag)
            JOptionPane.showMessageDialog(null,"Please Select A Table");
            
    }//GEN-LAST:event_ShowOrderbtnActionPerformed

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        // TODO add your handling code here:
        CustomerTabs.remove(0);
        CustomerTabs.add("Table",ReserveTable);
        CustomerTabs.add("Place Order",PlaceOrder);
    }//GEN-LAST:event_ResetbtnActionPerformed

    private void ConfirmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmbtnActionPerformed
        // TODO add your handling code here:
        order.setCustomerName(customer.getName());
        table.setOrder(order);
        orderlist.add(order);
        orders.setOrders(orderlist);
        tablelist.removeIf(var -> (var.getTableNum()== this.table.getTableNum()));
        tablelist.add(this.table);
        tables.setTables(tablelist);
        DATA.setTables(tables);
        DATA.setOrders(orders);
        try {
            DATA.writeData(Boot.jarParent);
        } catch (Exception ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFrame loginPage = new Start(DATA);
        loginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConfirmbtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        JFrame loginPage = new Start(DATA);
        this.dispose();
        loginPage.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private JToggleButton B1;
    private JToggleButton B2;
    private JToggleButton B3;
    private JToggleButton B4;
    private JToggleButton B5;
    private JToggleButton B6;
    private JToggleButton B7;
    private javax.swing.JButton Back;
    private javax.swing.JButton Confirmbtn;
    private javax.swing.JTabbedPane CustomerTabs;
    private javax.swing.JTextArea Details;
    private javax.swing.JList<String> DishList;
    private javax.swing.JPanel OrderDetails;
    private javax.swing.JList<String> OrderList;
    private javax.swing.JPanel PlaceOrder;
    private javax.swing.JButton PlaceOrderbtn;
    private javax.swing.JButton Removebtn;
    private javax.swing.JPanel ReserveTable;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JButton ShowOrderbtn;
    private javax.swing.JButton Showbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup jButtonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
